groups:
  - name: node_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 60
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alta carga de CPU en {{ $labels.instance }}"
          description: "Uso de CPU por encima de 60% por 5 minutos"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alta carga de memoria en {{ $labels.instance }}"
          description: "Uso de memoria por encima de 90% por 5 minutos"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"} * 100) < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Almacenamiento bajo en {{ $labels.instance }}"
          description: "Almacenamiento libre por debajo de 10% en {{ $labels.mountpoint }}"
